version: '3.8'

services:
  bitespeed-identity-service:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bitespeed_identity
      - DB_USER=postgres
      - DB_PASSWORD=password
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - bitespeed-network

  postgres:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_DB=bitespeed_identity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - bitespeed-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d bitespeed_identity']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  bitespeed-network:
    driver: bridge
